// const MovieActionTypes = {
//   SET_MOVIE_DATA_START: 'SET_MOVIE_DATA_START',
//   SET_MOVIE_DATA: 'SET_MOVIE_DATA',
//   SET_MOVIE_GRID_DATA: 'SET_MOVIE_GRID_DATA',
//   SET_MOVIE_DATA_SUCCESS: 'SET_MOVIE_DATA_SUCCESS',
//   SET_MOVIE_ADDITIONAL_DATA_SUCCESS: 'SET_MOVIE_ADDITIONAL_DATA_SUCCESS',
//   SET_MOVIE_ADDITIONAL_DATA: 'SET_MOVIE_ADDITIONAL_DATA'
// };

// export default MovieActionTypes;
const SET_MOVIE_DATA_START = 'SET_MOVIE_DATA_START'
const SET_MOVIE_DATA = 'SET_MOVIE_DATA'
const SET_MOVIE_GRID_DATA = 'SET_MOVIE_GRID_DATA'
const SET_MOVIE_DATA_SUCCESS = 'SET_MOVIE_DATA_SUCCESS'
const SET_MOVIE_ADDITIONAL_DATA_SUCCESS = 'SET_MOVIE_ADDITIONAL_DATA_SUCCESS'
const SET_MOVIE_ADDITIONAL_DATA = 'SET_MOVIE_ADDITIONAL_DATA'
const MovieActionTypes = {
  SET_MOVIE_DATA_START:SET_MOVIE_DATA_START,
  SET_MOVIE_DATA:SET_MOVIE_DATA,
  SET_MOVIE_GRID_DATA:SET_MOVIE_GRID_DATA,
  SET_MOVIE_DATA_SUCCESS:SET_MOVIE_DATA_SUCCESS,
  SET_MOVIE_ADDITIONAL_DATA_SUCCESS:SET_MOVIE_ADDITIONAL_DATA_SUCCESS,
  SET_MOVIE_ADDITIONAL_DATA:SET_MOVIE_ADDITIONAL_DATA
}
export default MovieActionTypes