// const TVActionTypes = {
//   SET_TV_DATA: 'SET_TV_DATA',
//   SET_TV_GRID_DATA: 'SET_TV_GRID_DATA',
//   SET_TV_DATA_SUCCESS: 'SET_TV_DATA_SUCCESS',
//   SET_TV_ADDITIONAL_DATA: 'SET_TV_ADDITIONAL_DATA'

// };

// export default TVActionTypes;
const SET_TV_DATA = 'SET_TV_DATA '
const SET_TV_GRID_DATA = 'SET_TV_GRID_DATA'
 const  SET_TV_DATA_SUCCESS = 'SET_TV_DATA_SUCCESS'
 const SET_TV_ADDITIONAL_DATA = 'SET_TV_ADDITIONAL_DATA'


const TVActionTypes = {
  SET_TV_DATA: SET_TV_DATA,
  SET_TV_GRID_DATA: SET_TV_GRID_DATA,
  SET_TV_DATA_SUCCESS: SET_TV_DATA_SUCCESS,
  SET_TV_ADDITIONAL_DATA: SET_TV_ADDITIONAL_DATA

};

export default TVActionTypes;